services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${WEB_CONTAINER_NAME}
    volumes:
      - ./projects/:/var/www/html
    ports:
      - "80:80"
    environment:
      COMPOSER_HOME: "/root/.composer"
  mysql:
    container_name: ${DB_CONTAINER_NAME}
    image: mysql:8.0
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"

volumes:
  db_data:
